dist: xenial
language: python
cache: pip
stages:
- quick-checks
- test
- if: tag =~ ^v\d
  name: deploy
script:
  - python -m pip install -e .[tests]
  - make $CHECK
matrix:
  fast_finish: true
  include:
  - python: 3.6
    stage: quick-checks
    env: CHECK="lint"
  - python: 3.6
    stage: test
    env: CHECK="test"
  - python: 3.7
    stage: test
    env: CHECK="test"
  - python: 3.7
    stage: deploy
    env: DEPLOY_TO_PYPI=yes
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: a+Nrm9S5bPYEiupyWDJqMey4XEh6ZMGqcKJaUQ61DqhRg67Zj8iGY0igmvFaWEpj2BJXYuuv1TMVPZVAVAOwm6SygowSFHNV8GKGW/eGOTQP9K+AluDk/7RWJoYr3pq1Gz/zwAXPROZbXjo1+APF1CUoknobfl6srz59qMnE+SniS2nH73lsnAxvpCiCbtCXipn5z2nVkxk3OiJe/pcNV4jSg5d00vkYrMcmLHWjFQWXyqSd49dXAfjFd0NxFv/15YNUimCv4UovP/W55+Y5jGwvYQ4zWDC10NAiJwMB4bGE7qCBRpWD1PKOPUlCqp5kizcM+Kj/QMfetY+F1KJX5xuceI9efvVHG6dZqdickYUmZqupEveJkRQZ3adJAI4JjSEQnWNcpa6t3yxbRBXNXHqZTHyC8YSx2ZeRbfXfe4KB8pKgXD2RxqPmZaxqylxd68PhWHZWegnpE5a2qsW56rz2NoEU8nEFMDoa4+5bm233yw8V1KjTgXle1A/7nCAhJtwKATTk1xj6XbCJBL89FWmSF/ze3UBWcSYxwEfU2eHFaP3bkt1f8qKJg79AfsJufZZyj2yhxMkA0DS0D8L7O/TpgE6HyN4HQXxcGoQcTbs2ZCNZGWJNvHYBkeSpYxR0MLUXxG3wv1KpkcgZRfHtF7mkFX9EeNyzAU5xF1/TEn0=
  on:
    tags: true
    branch: master
    condition: "$DEPLOY_TO_PYPI = yes"
    skip_existing: true
